// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://snthtdlcxzqqzfncnddn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNudGh0ZGxjeHpxcXpmbmNuZGRuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2MjE0NjQsImV4cCI6MjA2ODE5NzQ2NH0.N9GekUTHPzDNdv_R51-xFgsoHMKcnZegj_KZQ2Jk6rE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});