// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ittoxabtgyeofriognxt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml0dG94YWJ0Z3llb2ZyaW9nbnh0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1OTkyODIsImV4cCI6MjA2ODE3NTI4Mn0.xyErHX0H-TBwT47e6deM9MPhQsRgZEVD1JFD0PO3Ycw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});